"""child

Revision ID: d3b2b923571d
Revises: 61e1ebb9387a
Create Date: 2022-06-14 11:38:26.597895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3b2b923571d'
down_revision = '61e1ebb9387a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detail',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=230), nullable=True),
    sa.Column('be_python_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['be_python_id'], ['BE_PYTHON.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detail')
    # ### end Alembic commands ###
